### PR TITLE
Update to 42 runtime

### PR DESCRIPTION
**Pull request by ZanderBrown**
Now bundles Clutter, since it's no longer part of the runtime

### CODE REVIEW

**Comment by hfiguiere** [comment]
Doesn't seem to be fatal, but I get:

```
(pinpoint:2): Clutter-CRITICAL **: 10:36:15.861: Unable to create dummy onscreen: No foreign surface, and wl_shell unsupported by the compositor
```

Even then it might not be new.

**Comment by hfiguiere** [comment]
btw clutter is in shared-modules, it's probably better to use that.

**Comment by ZanderBrown** [comment]
So it is, didn't think to check if it had been added since I last looked. However what I've got here is based on the g-b-m definitions, with added cleanups, producing a 4MB installed-size flatpak. The definitions in shared-modules produce a flatpak around 10x that, — and pinpoint itself is all of about 400k.

Of course ultimately it probably doesn't matter much

re log:
The current/stable/3.38 flatpak has the same, so I think that's just clutter being clutter

**Comment by hfiguiere** [comment]
if the warning did exist before, then it's fine. thanks!

**Pull request merged**
